### ISSUE TITLE
Accessibility: Keyboard Focus and Control

### ISSUE THREAD

**Issue by normanbrobinson** [gorork/paper-audio-player#14]
The current demo looses focus when play or pausing using the keyboard.
1. Tab to focus on player.
2. Press enter (or space key) to play.
3. Focus moves to top of demo page; tabbing twice returns to focus on player.

NOTE: it would be useful (perhaps another feature request?) to be more accessible and provide keyboard access to use arrow keys, page up/down keys, to move through the audio stream as current users do now by clicking in the player graphic area.

**Comment by gorork** [comment]
@normanbrobinson Thanks for reporting!
