### ISSUE TITLE
Issues with Desktop Chrome, Safari for iOS goes mildly smooth

### ISSUE THREAD

**Issue by TheElectroclassics** [gorork/paper-audio-player#35]
http://the-electroclassic.com.mx/2decades/

This is the page I'm testing right now. For some reason it doesn't show in Chrome (Latest Version, Windows 10 Annivesary Update) but it does kinda show up in Safari for iOS. Is anyone else having the same problem?

I got CloudFlare to work in development mode, but it doesn't work either

**Comment by gorork** [comment]
@TheElectroclassics Try loading *webcomponents-lite.js* library before player element. The order in the [usage](https://github.com/gorork/paper-audio-player#usage) part matters.

**Comment by TheElectroclassics** [comment]
I placed the webcomponents, all the way up in the head tag, but still not working.

**Comment by TheElectroclassics** [comment]
In mobile I can see the player, but not on desktop.

**Comment by gorork** [comment]
Closing this one, as it was not possible to reproduce.
